[project]
name = "python-intl"
version = "0.9.0"
description = "Python implementation of the Intl JavaScript API"
readme = "README.md"
authors = [
    { name = "David Danier", email = "david.danier@gmail.com" }
]
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "pyicu>=2.16.2",
]

[project.urls]
Repository = "https://github.com/ddanier/python-intl"

[dependency-groups]
dev = [
    "basedpyright>=1.40.1",
    "mypy>=2.3.1",
    "pylsp-mypy>=0.8.0",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
    "python-lsp-server>=1.15.0",
    "ruff>=0.16.3",
    "tox>=4.60.0",
    "ty>=0.0.72",
]

[tool.uv.sources]
pyicu = { git = "https://gitlab.pyicu.org/main/pyicu.git", rev = "0cf41ac262ad486228d9695f3b425008b3cfe9ef" }

[tool.pytest.ini_options]
markers = [
    "unit: mark a test as a unit test",
    "node: mark tests jun against the node/JS implementation",
]

[tool.ruff]
line-length = 115
output-format = "grouped"

[tool.ruff.lint]
select = [
    "A",     # flake8-builtins
    "ANN",   # flake8-annotations
    "ARG",   # flake8-unused-arguments
    "ASYNC", # flake8-async
    "B",     # flake8-bugbear
    "BLE",   # flake8-blind-except
    "C4",    # flake8-comprehensions
    "COM",   # flake8-commas
    "DTZ",   # flake8-datetimez
    "E",     # pycodestyle errors
    "EM",    # flake8-errmsg
    "EXE",   # flake8-executable
    "F",     # pyflakes
    "FA",    # flake8-future-annotations
    "FBT",   # flake8-boolean-trap
    "FURB",  # refurb
    "I",     # isort
    "ICN",   # flake8-import-conventions
    "ISC",   # flake8-implicit-str-concat
    "N",     # pep8-naming
    "PERF",  # perflint
    "PIE",   # flake8-pie
    "PL",    # pylint
    "PT",    # flake8-pytest-style
    "PTH",   # flake8-use-pathlib
    "Q",     # flake8-quotes
    "RSE",   # flake8-raise
    "RUF",   # ruff-specific rules
    "S",     # flake8-bandit
    "SIM",   # flake8-simplify
    "SLOT",  # flake8-slots
    "T10",   # flake8-debugger
    "T20",   # flake8-print
    "TC",    # flake8-type-checking
    "TD",    # flake8-todos
    "TID",   # flake8-tidy-imports
    "TRY",   # tryceratops
    "UP",    # pyupgrade
    "W",     # pycodestyle warnings
]
ignore = [
    "N812", # Allow using "import python_intl as Intl"
]

[tool.ruff.lint.per-file-ignores]
"test_*.py" = [
    "S101",   # Allow usage of assert in tests
    "ANN201", # Don't require to define return types in tests
]
"conftest.py" = [
    "S101",   # Allow usage of assert in tests
    "ANN201", # Don't require to define return types in tests
]

[tool.ruff.lint.isort]
combine-as-imports = true
force-wrap-aliases = true

[tool.ty.analysis]
replace-imports-with-any = ["icu.**"]

[[tool.mypy.overrides]]
module = ["icu.*"]
ignore_missing_imports = true

[tool.basedpyright]
pythonVersion = "3.12"
reportAny = false
reportMatchNotExhaustive = false
reportUnknownLambdaType = false
reportPrivateUsage = false
# The following are only necessary cause of untyped icu library
allowedUntypedLibraries = ["icu"]
reportAttributeAccessIssue = false
reportUnknownVariableType = false
reportUnknownMemberType = false
reportUnknownParameterType = false
reportUnknownArgumentType = false

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = "python_intl"
module-root = ""
